#.github\workflows\issue_commented.yml
on:
  issue_comment:
    types: [ created ]
  workflow_dispatch:
name: Commented Pull Request
jobs:
  pullRequestHandler:
    name: Pull Request Validator
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main
    - name: Pull Request Validator
      uses: shovel-org/GithubActions@main
      if: startsWith(github.event.comment.body, '/verify')
      env:
        GITH_EMAIL: addie@pigsflew.com
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
